
# read EML files and parse into table with title, abstract, keywords

library(xml2)
library(tidyverse)

# folder with EML files, not in git (generated by running "get_eml_files")

eml_path <- "eml_files"

output_path <- "parsed_eml"

# Identify downloaded XMLs
file_names <- list.files(path = eml_path, pattern = '*.xml')

# Create empty dataframe to store content in
df <- data.frame(fileName = character(0),
                 title = character(0),
                 abstract = character(0),
                 keywords = character(0),
                 entity_info = character(0),
                 attribute_info = character(0),
                 stringsAsFactors = FALSE) 

# For each file...
for (i in 1:length(file_names)) {
  
  # Get the path to the file
  file_name <- file.path(eml_path, file_names[i])
  
  # Read in that file
  
  xml_file <- read_xml(file_name)
  
  # Strip out some key components of that XML file
  eml_title <- xml_text(xml_find_first(xml_file, './/title'))
  eml_title <- str_replace_all(eml_title, '\\n', ' ')
  eml_title <- str_replace_all(eml_title, '\\W', ' ')
  
  eml_abstract <- xml_text(xml_find_first(xml_file, './/abstract'))
  eml_abstract <- str_replace_all(eml_abstract, '\\n', ' ')
  eml_abstract <- str_replace_all(eml_abstract, '\\W', ' ')
  
  eml_keywords <- xml_text(xml_find_all(xml_file, './/keyword'))
  all_keywords <- paste(eml_keywords, collapse=" ")
  all_keywords <- str_replace_all(all_keywords, '\\n', ' ')
  all_keywords <- str_replace_all(all_keywords, '\\W', ' ')
  
  eml_entity <- xml_text(xml_find_all(xml_file, './/entityDescription'))
  all_entities <- paste(eml_entity, collapse = ' ')
  all_entities <- str_replace_all(all_entities, '\\n', ' ')
  all_entities <- str_replace_all(all_entities, '\\W', ' ')
  
  #some of these are repeating a lot of text, cut them down to fit a  csv cell
  all_entities <- str_sub(all_entities, 1, 5000)
  
  eml_attribute_def <- xml_text(xml_find_all(xml_file, './/attributeDefinition'))
  eml_attribute_label <- xml_text(xml_find_all(xml_file, './/attributeLabel'))
  all_attribute_defs <- paste(eml_attribute_def, collapse = ' ')
  all_attribute_labels <- paste(eml_attribute_label, collapse = ' ')
  all_attributes <- paste(all_attribute_defs, all_attribute_defs, sep = ' ')
  all_attributes <- str_replace_all(all_attributes, '\\n', ' ')
  all_attributes <- str_replace_all(all_attributes, '\\W', ' ')
  all_attributes <- str_squish(all_attributes)
  all_attributes <- str_sub(all_attributes, 1, 5000)
  
  # Store them in a dataframe
  df_part <- data.frame(fileName = file_names[i],
                        title = eml_title,
                        abstract = eml_abstract,
                        keywords = all_keywords,
                        entity_info = all_entities,
                        attribute_info = all_attributes)
  
  # Attach that dataframe to the larger dataframe of all files
  df <- rbind(df, df_part)
}

# Wrangle metadata from this CSV
df_metadata <- df %>%
  separate(fileName, into = c('scope', 'package_id', 'version', NA), sep = '\\.') %>%
  mutate(packageid = paste(scope, package_id, sep = '.')) %>%
  select(packageid, title, keywords, abstract,entity_info, attribute_info)

# Export this
write.csv(df_metadata, file = file.path(output_path, 'datasetKeywords.csv'), row.names = F)
